services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
  - type: web
    name: frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: npm start